name: workflow_name

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: get change files
        run: |
          echo "start run test"
          echo "current  SHA: $GITHUB_SHA"
          echo "previous SHA: ${{ github.event.before }}"
          echo "-- 1 -- "
          git diff --name-only ${{ github.event.before }} $GITHUB_SHA
          echo "-- 2 -- "
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} $GITHUB_SHA)
          echo "-- 3 -- "
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
          echo "-- 4 -- "

      - name: echo change files
        env: 
          CHANGED_FILES: ${{ env.changed_files }}
        run: |
          for file in $CHANGED_FILES; do
            echo "processing $file"
          done
        