name: workflow_name

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get change files
        run: |
          echo "start run test"
          echo "current  SHA: $GITHUB_SHA"
          echo "previous SHA: ${{ github.event.before }}"
          CHANGE_FILES=$(git diff --name-only ${{ github.event.before }} $GITHUB_SHA)
          echo "changed_files=$CHANGE_FILES" >> $GITHUB_ENV

      - name: echo change files
        env: 
          CHANGED_FILES: ${{ env.changed_files }}
        run: |
          for file in $CHANGED_FILES; do
            echo "processing $file"
          done
        